### PR TITLE
Upgrade ruby 3 and rails 6

### LINKED ISSUE #370: Upgrade to ruby 3 and rails 6

### PR DESCRIPTION
**Pull request by crowesn**
Resolves #370

### CODE REVIEW

**Review by hortongn — COMMENTED** [review]
@crowesn Everything checks out in my local environment.  App runs and tests pass.  Two things to test/consider before merging:

In Brandon's ruby/rails upgrade PR on AAEC, he had to also upgrade Capistrano to 3.17.11 and tweak the capistrano config files to get it working.  I think it's worth you trying a deploy of this branch to libappstest to verify deploy isn't broken.  That will also let us know if anything is broken in production mode after this upgrade.  We want to ensure things like precompiling assets, etc. still work.  Trying the app on libappstest is the best way to know that all is well.

Brandon also added the 'bcrypt_pbkdf' and 'ed25519' gems to AAEC, which I think we needed to get capistrano working with the upgrade.

Also in Brandon's PR, he added webpacker.  That replaces sprockets as the default javascript compiler in Rails 6.  It's fine to stay with the old sprockets for now, but I suggest creating an issue to move to webpacker in the future.  Probably best to use the default tools that come with rails 6 and stay consistent.

**Comment by crowesn** [comment]
RUBY_CONFIGURE_OPTS="--disable-dtrace" rbenv install 3.0.5

**Comment by crowesn** [comment]
@hortongn 

I updated the Capistrano version and noted that the other apps in Brandon's aaec work are already present in this app. I didn't see sprockets listed in our Gemfile but I'll open an issue anyway and look into it. 

I installed ruby 3.0.5 in rbenv on libappstest and then was able to successfully deploy the branch. Looks good to me.

**Review by hortongn — APPROVED** [review]
@crowesn Glad the deploy is working.  Merging...

**Pull request merged**
