### PR TITLE
Replace search url with path helper

### LINKED ISSUE #314: Keyword Search leads to 404
The keyword search is broken on libappstest.

After hitting the search button, it sends us to a Page Not Found 404 error.

### PR DESCRIPTION
**Pull request by crowesn**
Fixes #314

### CODE REVIEW

**Comment by crowesn** [comment]
I attempted to make this code change manually on libappstest in order to test but I'm not sure how to restart the server etc. I think it's running in production mode and not registering the hotfix.

**Comment by hortongn** [comment]
@crowesn See Brandon's README here for command to restart the app on libappstest:
https://github.com/uclibs/rails-conf/tree/main/treatment_database#server-information

Sounds like `sudo systemctl restart puma-treatment-database.service` should do it.

**Comment by crowesn** [comment]
Thanks @hortongn ,

Test was successful on libappstest, I'll leave the change in place so reviewer can inspect?

**Comment by hortongn** [comment]
@crowesn Also, in your local environment you can start your rails server with `RAILS_RELATIVE_URL_ROOT=/treatment_database rails server` and visit http://localhost/treatment_database to test your fix on your machine.

**Comment by crowesn** [comment]
> @crowesn Also, in your local environment you can start your rails server with `RAILS_RELATIVE_URL_ROOT=/treatment_database rails server` and visit http://localhost/treatment_database to test your fix on your machine.

Yep, it works on local and libappstest.

**Review by hortongn — APPROVED** [review]

**Pull request merged**
