### PR TITLE
464 - Run rails db:migrate

### LINKED ISSUE #464: Update db:schema to match migrations
Somewhere along the line, the db:schema in the qa branch ended up not in alignment with the migrations that have been completed.  When `rails db:migrate` is run on the qa branch,these changes are shown:
Screenshot 2024-04-15 at 9 53 05 AM

### PR DESCRIPTION
**Pull request by Janell-Huyck**
Fixes #464 

These changes occurred with running `rails db:migrate`.

### CODE REVIEW

**Review by hortongn — COMMENTED** [review]
@Janell-Huyck When I checkout this branch and run a db:migrate locally, it undoes your schema.rb changes.  My db:migrate changed the types from `integer` back to `bigint`.  Not sure why it's behaving differently between our laptops.

This is the related migration file:
https://github.com/uclibs/treatment_database/blob/qa/db/migrate/20230405164303_create_active_storage_tables.active_storage.rb

**Comment by Janell-Huyck** [comment]
I don't think this is impacting anything directly, other than adding in new changes for me to ignore my PR's.  Strange indeed.  I'm ok with shelving this one for now and coming back to it at a later date.

**Comment by hortongn** [comment]
That works for me.  Thanks

**Comment by Janell-Huyck** [comment]
To return to at a later date.   Disregard for now.

**Pull request closed without merging**
