### PR TITLE
Improve worksheet pdf formatting

### LINKED ISSUE #429: Improve conservation worksheet formatting
```
Can the formatting of the Conservation Worksheet be improved including

1. Times New Roman text
2. Typeface size increased to 11 or 12 point
3. Move Item Record# further to the left to allow for more space for the fields, especially Collection, Call#, and Date In
4. Reformat date to be Month-Day-Year
5. Reload PDF of bottom of form to be clearer, PDF attached
```
Related #422

### PR DESCRIPTION
**Pull request by crowesn**
Resolves #429 

- [x] Times New Roman text
- [x] Typeface size increased to 11 or 12 point
- [x] Move Item Record# further to the left to allow for more space for the fields, especially Collection, Call#, and Date In
- [x] Reformat date to be Month-Day-Year
- [x] Reload PDF of bottom of form to be clearer, PDF attached

Sample pdfs: 

[Diseases of the sexual or_conservation_worksheet.pdf](https://github.com/uclibs/treatment_database/files/14464193/Diseases.of.the.sexual.or_conservation_worksheet.pdf)
[Joannis Garsiae Galleci &_conservation_worksheet.pdf](https://github.com/uclibs/treatment_database/files/14464195/Joannis.Garsiae.Galleci._conservation_worksheet.pdf)

### CODE REVIEW

**Comment by crowesn** [comment]
@Janell-Huyck This should be good to go once we get a thumbs up from the preservation lab and  https://github.com/uclibs/treatment_database/pull/433 is merged.

**Comment by crowesn** [comment]
@Janell-Huyck still holding for feedback from preservation lab.

**Comment by crowesn** [comment]
Preservation lab gives thumbs up, this is ready to go.

**Review by Janell-Huyck — APPROVED** [review]
🚀 

Looks good!  Merging...

**Pull request merged**
